services:
  mongodb:
    image: "mongo:${MONGO_VERSION:-latest}"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=notes-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 1s
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8000
    container_name: frontend
    restart: always
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
