services:
  mongodb:
    image: "mongo:${MONGO_VERSION:-latest}"
    container_name: mongodb
    restart: always
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
