// This file is auto-generated by @hey-api/openapi-ts

export type CreateNoteApiRequest = {
    title: string;
    content: string;
};

export type DefaultApiResponse = {
    message: string;
};

export type GetAllNotesApiResponse = {
    notes: Array<GetAllNotesResponse>;
};

/**
 * Response model for getting all notes.
 */
export type GetAllNotesResponse = {
    title: string;
    note_id: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthApiResponse = {
    status: string;
};

/**
 * Note model.
 */
export type Note = {
    title: string;
    content: string;
    note_id: string;
    version: number;
};

export type RollbackNoteApiRequest = {
    version: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: DefaultApiResponse;
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/';
};

export type HealthApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthApiResponse;
};

export type HealthApiV1HealthGetResponse = HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type GetNotesApiV1NotesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notes/';
};

export type GetNotesApiV1NotesGetResponses = {
    /**
     * Successful Response
     */
    200: GetAllNotesApiResponse;
};

export type GetNotesApiV1NotesGetResponse = GetNotesApiV1NotesGetResponses[keyof GetNotesApiV1NotesGetResponses];

export type CreateOneNoteApiV1NotesPostData = {
    body: CreateNoteApiRequest;
    path?: never;
    query?: never;
    url: '/api/v1/notes/';
};

export type CreateOneNoteApiV1NotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOneNoteApiV1NotesPostError = CreateOneNoteApiV1NotesPostErrors[keyof CreateOneNoteApiV1NotesPostErrors];

export type CreateOneNoteApiV1NotesPostResponses = {
    /**
     * Successful Response
     */
    200: DefaultApiResponse;
};

export type CreateOneNoteApiV1NotesPostResponse = CreateOneNoteApiV1NotesPostResponses[keyof CreateOneNoteApiV1NotesPostResponses];

export type DeleteOneNoteApiV1NotesNoteIdDeleteData = {
    body?: never;
    path: {
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type DeleteOneNoteApiV1NotesNoteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOneNoteApiV1NotesNoteIdDeleteError = DeleteOneNoteApiV1NotesNoteIdDeleteErrors[keyof DeleteOneNoteApiV1NotesNoteIdDeleteErrors];

export type DeleteOneNoteApiV1NotesNoteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DefaultApiResponse;
};

export type DeleteOneNoteApiV1NotesNoteIdDeleteResponse = DeleteOneNoteApiV1NotesNoteIdDeleteResponses[keyof DeleteOneNoteApiV1NotesNoteIdDeleteResponses];

export type GetOneNoteApiV1NotesNoteIdGetData = {
    body?: never;
    path: {
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type GetOneNoteApiV1NotesNoteIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOneNoteApiV1NotesNoteIdGetError = GetOneNoteApiV1NotesNoteIdGetErrors[keyof GetOneNoteApiV1NotesNoteIdGetErrors];

export type GetOneNoteApiV1NotesNoteIdGetResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type GetOneNoteApiV1NotesNoteIdGetResponse = GetOneNoteApiV1NotesNoteIdGetResponses[keyof GetOneNoteApiV1NotesNoteIdGetResponses];

export type UpdateOneNoteApiV1NotesNoteIdPutData = {
    body: CreateNoteApiRequest;
    path: {
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type UpdateOneNoteApiV1NotesNoteIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOneNoteApiV1NotesNoteIdPutError = UpdateOneNoteApiV1NotesNoteIdPutErrors[keyof UpdateOneNoteApiV1NotesNoteIdPutErrors];

export type UpdateOneNoteApiV1NotesNoteIdPutResponses = {
    /**
     * Successful Response
     */
    200: Note;
};

export type UpdateOneNoteApiV1NotesNoteIdPutResponse = UpdateOneNoteApiV1NotesNoteIdPutResponses[keyof UpdateOneNoteApiV1NotesNoteIdPutResponses];

export type RollbackOneNoteApiV1NotesNoteIdRollbackPostData = {
    body: RollbackNoteApiRequest;
    path: {
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/rollback';
};

export type RollbackOneNoteApiV1NotesNoteIdRollbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RollbackOneNoteApiV1NotesNoteIdRollbackPostError = RollbackOneNoteApiV1NotesNoteIdRollbackPostErrors[keyof RollbackOneNoteApiV1NotesNoteIdRollbackPostErrors];

export type RollbackOneNoteApiV1NotesNoteIdRollbackPostResponses = {
    /**
     * Successful Response
     */
    200: DefaultApiResponse;
};

export type RollbackOneNoteApiV1NotesNoteIdRollbackPostResponse = RollbackOneNoteApiV1NotesNoteIdRollbackPostResponses[keyof RollbackOneNoteApiV1NotesNoteIdRollbackPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};